CREATE TABLE `People` (
    `Id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Name` VARCHAR(255) NOT NULL
);

CREATE TABLE `Pets` (
    `Id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `PersonId` INT NOT NULL,
    `Name` VARCHAR(255) NOT NULL UNIQUE,
    CONSTRAINT FK_People_Pets FOREIGN KEY (`PersonId`) REFERENCES `People`(`Id`)
);