name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Restore
        run: |
          dotnet restore TxCommand/TxCommand.csproj
          dotnet restore TxCommand.Tests/TxCommand.Tests.csproj

      - name: Build TxCommand
        run: dotnet build -c Release --no-restore TxCommand/TxCommand.csproj

      - name: Build TxCommand.Abstractions
        run: dotnet build -c Release --no-restore TxCommand.Abstractions/TxCommand.Abstractions.csproj

      - name: Unit Test
        run: dotnet test TxCommand.Tests/TxCommand.Tests.csproj

      - name: Pack TxCommand
        run: dotnet pack -c Release --no-restore --no-build TxCommand/TxCommand.csproj

      - name: Pack TxCommand.Abstractions
        run: dotnet pack -c Release --no-restore --no-build TxCommand.Abstractions/TxCommand.Abstractions.csproj

      - name: Upload Artifacts
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: nuget
          path: "**.nupkg"

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull Database Image
        run: docker pull mcr.microsoft.com/mssql/server:2017-CU17-ubuntu

      - name: Restore
        run: dotnet restore Example/TxCommand.Example.IntegrationTests/TxCommand.Example.IntegrationTests.csproj

      - name: Build
        run: dotnet build --no-restore Example/TxCommand.Example.IntegrationTests/TxCommand.Example.IntegrationTests.csproj

      - name: Test
        run: dotnet test Example/TxCommand.Example.IntegrationTests/TxCommand.Example.IntegrationTests.csproj

  publish:
    name: Publish
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: nuget
          path: packages/

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Publish
        run: dotnet nuget push packages/*.nupkg ${{secrets.NUGET_API_KEY}} -Source https://api.nuget.org/v3/index.json
